var LanguageEnglish = {
  "languageCSS":"english",
  "ABOUT": "About",
  "Fixtures & Results": "Fixtures & Results",
  "Fixtures": "Fixtures",
  "Players": "Players",
  "Photo Gallery": "Photo Gallery",
  "Wallpapers": "Wallpapers",
  "News": "News",
  "Tickets & Merchandise": "Tickets & Merchandise",
  "Fan Corner": "Fan Corner",
  "SEASON 3 REVIEW": "SEASON 3 REVIEW",
  "Photo Gallery": "Photo Gallery",
  "KNOW YOUR PANTHERS": "KNOW YOUR PANTHERS",
  "WALLPAPERS": "WALLPAPERS",
  "NEWS & MEDIA": "NEWS & MEDIA",
  "VIEW STORY": "VIEW STORY",
  "SOCIAL HUB": "SOCIAL HUB",
  "Get exclusive JPP Wallpapers for your Desktop and Mobile": "Get exclusive JPP Wallpapers for your Desktop and Mobile",
  "Download Wallpapers": "Download Wallpapers",
  "Download the JPP App": "Download the JPP App",
  "CLICK HERE": "CLICK HERE",
  "Jaipur Pink Panthers is a professional kabaddi team based in Jaipur, Rajasthan that competes in the Pro Kabaddi League.": "Jaipur Pink Panthers is a professional kabaddi team based in Jaipur, Rajasthan that competes in the Pro Kabaddi League.",
  "Founded": "Founded",
  "2016": "2016",
  "Owner": "Owner",
  "Abhishek Bachchan": "Abhishek Bachchan",
  "Coach": "Coach",
  "Kasinathan Baskaran": "Kasinathan Baskaran",
  "Captain": "Captain",
  "Navneet Gautam": "Navneet Gautam",
  "Home ground": "Home ground",
  "Sawai Mansingh stadium": "Sawai Mansingh stadium",
  "Jaipur": "Jaipur",
  "Jaipur Pink Panthers are the champions of the first season of the Pro Kabaddi League in 2014.": "Jaipur Pink Panthers are the champions of the first season of the Pro Kabaddi League in 2014.",
  "SIGN UP": "SIGN UP",
  "Register and get a chance to win exclusive Jaipur Pink Panther merchandise, meet and greet with the players and win home match tickets.": "Register and get a chance to win exclusive Jaipur Pink Panther merchandise, meet and greet with the players and win home match tickets.",
  "First Name": "First Name",
  "Last Name": "Last Name",
  "Mobile Number": "Mobile Number",
  "Email Address": "Email Address",
  "City": "City",
  "Anil Patil": "Anil Patil",
  "Mohammad Maghsodlou": "Mohammad Maghsodlou",
  "Rohit Rana": "Rohit Rana",
  "Choose Your Favourite Panthers": "Choose Your Favourite Panthers",
  "C. Arun": "C. Arun",
  "Sanjay Shrestha": "Sanjay Shrestha",
  "Gangadhari Mallesh": "Gangadhari Mallesh",
  "Rajesh Narwal": "Rajesh Narwal",
  "Samarjeet Singh": "Samarjeet Singh",
  "Jagdeesha K.K": "Jagdeesha K.K",
  "Raju Lal Choudhary": "Raju Lal Choudhary",
  "Sonu Narwal": "Sonu Narwal",
  "Jasvir Singh": "Jasvir Singh",
  "Ran Singh": "Ran Singh",
  "Wei Yang Tsai": "Wei Yang Tsai",
  "Kuldeep Singh": "Kuldeep Singh",
  "Rohit Kumar Prajapat": "Rohit Kumar Prajapat",
  "SUBMIT": "SUBMIT",
  "Registration Successfull": "Registration Successfull",
  "Stay tuned to our weekly contests on social media and stand a chance to win exclusive merchandise": "Stay tuned to our weekly contests on social media and stand a chance to win exclusive merchandise",
  "is required": "is required",
  "Invalid": "Invalid",
  "Desktop": "Desktop",
  "ANDROID": "ANDROID",
  "IOS": "IOS",
  "BUY NOW": "BUY NOW",
};

var LanguageHindi = {
  "languageCSS":"hindi",
  "ABOUT": "बारे में",
  "About": "बारे में",
  "Fixtures & Results": "प्रतियोगिता एवं परिणाम",
  "Fixtures": "प्रतियोगिता",
  "Players": "खिलाड़ी",
  "Photo Gallery": "गैलरी वॉलपेपर",
  "JPP TV": "JPP TV",
  "Wallpapers": "वॉलपेपर",
  "News": "समाचार",
  "Tickets & Merchandise": "टिकट एवं वस्तुएं",
  "Tickets": "टिकट",
  "&": "एवं",
  "Merchandise": "वस्तुएं",
  "Fan Corner": "प्रशंसकों के लियें",
  "SEASON 3 REVIEW": "सीज़न 3 की समीक्षा",
  "Photo Gallery": "गैलरी देखें",
  "KNOW YOUR PANTHERS": "हमारे पैंथर्स",
  "WALLPAPERS": "वॉलपेपर्स",
  "NEWS & MEDIA": "ख़बर एवं मीडिया ",
  "VIEW STORY": "और अधिक जानें ",
  "SOCIAL HUB": "सामाजिक केंद्र",
  "Get exclusive JPP Wallpapers for your Desktop and Mobile": "अपने डेस्कटॉप /कम्प्यूटर और मोबाइल के लिए विशेष JPP वॉलपेपर पाएँ",
  "Download Wallpapers": "वॉलपेपर डाउनलोड करें",
  "Download the JPP App": "JPP ऐप डाउनलोड करें",
  "CLICK HERE": "प्रवेश करें",
  "Jaipur Pink Panthers is a professional kabaddi team based in Jaipur, Rajasthan that competes in the Pro Kabaddi League.": "जयपुर पिंक पैन्थर्स जयपुर,राजस्थान स्थित एक पेशेवर  कबड्डी टीम है , जो प्रो - कबड्डी  लीग में हिस्सा लेती है ।",
  "Founded": "स्थापना",
  "2016": "2014",
  "Owner": "मालिक",
  "Abhishek Bachchan": "अभिषेक बच्चन ",
  "Coach": "कोच ",
  "Kasinathan Baskaran": "काशीनाथन भास्करन",
  "Captain": "कैप्टन ",
  "Navneet Gautam": "नवनीत गौतम ",
  "Home ground": "होम ग्राउंड",
  "Sawai Mansingh stadium": "सवाई मानसिंग स्टेडियम",
  "Jaipur": "जयपुर",
  "Jaipur Pink Panthers are the champions of the first season of the Pro Kabaddi League in 2014.": "जयपुर पिंक पैन्थर्स प्रो-कबड्डी  लीग -2014 के प्रथम सीज़न के चैम्पियन्स हैं ।",
  "SIGN UP": "शामिल हों ",
  "Register and get a chance to win exclusive Jaipur Pink Panther merchandise, meet and greet with the players and win home match tickets.": "पंजीकरण करें और जयपुर पिंक पैन्थर के विशिष्ट सामान जीतने का , खिलाड़ियों से मिलने एवं उनका अभिवादन करने का मौका पायें और घरेलू मैचों की टिकट जीतें ।  ",
  "First Name": "प्रथम नाम",
  "Last Name": "उपनाम",
  "Mobile Number": "मोबाइल नंबर ",
  "Email Address": "ईमेल ऐड्रेस ",
  "City": "शहर",
  "Anil Patil": "अनिल पाटिल ",
  "Mohammad Maghsodlou": "मोहम्मद मकसूदलौ ",
  "Rohit Rana": "रोहित राणा  ",
  "Choose Your Favourite Panthers": "अपना पसंदीदा पैन्थर चुनें ",
  "C. Arun": "सी . अरुण ",
  "Sanjay Shrestha": "संजय श्रेष्ठा ",
  "Gangadhari Mallesh": "गंगाधारी मल्लेश",
  "Rajesh Narwal": "राजेश नरवाल ",
  "Samarjeet Singh": "राजेश नरवाल ",
  "Jagdeesha K.K": "राजेश नरवाल ",
  "Raju Lal Choudhary": "राजेश नरवाल ",
  "Sonu Narwal": "सोनू नरवाल",
  "Jasvir Singh": "जसवीर सिंह  ",
  "Ran Singh": "रण सिंह",
  "Wei Yang Tsai": "वी यांग सैय",
  "Kuldeep Singh": "कुलदीप सिंह",
  "SUBMIT": "दाखिल करें",
  "Registration Successfull": "पंजीकरण सफलें",
  "Rohit Kumar Prajapat": "रोहित कुमार प्रजापत",
  "Stay tuned to our weekly contests on social media and stand a chance to win exclusive merchandise": "सोशल मीडिया पर हमारी साप्ताहिक प्रतियोगिता देखते रहें और ढेरों सामान जीतने का मौका पायें !",
  "is required": "आवश्यक है",
  "Invalid": "अमान्यै",
  "Desktop": "डेस्कटॉप",
  "ANDROID": "एंड्रॉयड",
  "IOS": "आईओएस",
  "BUY NOW": "आईओएस",
  "COMING SOON": "आईओएस",
};
